language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - tip
install:
  - mkdir -p $HOME/gopath/src/github.com/kyani-inc
  - cd $HOME/gopath/src/github.com/kyani-inc/storage
  - go get -t ./...
  - go test ./...
